[workspace]
members = [
  "base",
  "aoc23"
]
resolver = "2"

[workspace.dependencies]
log = "0.4.20"
pretty_env_logger = "0.5.0"
regex = "1.10.2"

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
